<?php

namespace SubwayBuddy\UserBundle\Entity;

/**
 * ChatroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatroomRepository extends \Doctrine\ORM\EntityRepository
{
}
